<a href="https://colab.research.google.com/github/Nayan-Bebale/DSA-Practice/blob/main/3_2_arrayMatrixHashmap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Array, Matrix and hashing

<a href="https://neetcode.io/roadmap">NeetCode Roadmap</a>

In [ ]:
import numpy as np

In [ ]:
array1D = np.array([1, 2, 3, 4])
print(array1D)
print(array1D.ndim)

[1 2 3 4]
1


In [ ]:
# Access the specific element
n = 3
print(array1D[2])

3


In [ ]:
array2D = np.array([
    [1, 2, 3, 4],
    [11, 12, 13, 14],
    [21, 22, 23, 24],
    [31, 32, 33, 34]
])
print(array2D.ndim)

2


In [ ]:
# Access the specific element
n = 23
print(array2D[2][2])
print(array2D.shape)

23
(4, 4)


In [ ]:
array3D = np.array([
    [
        [1, 2, 3],
        [8, 9, 0],
        [28, 29, 20],
        [58, 59, 50]
    ],
    [
        [11, 12, 13],
        [18, 19, 10],
        [38, 39, 30],
        [48, 49, 40]
    ]
])
print(array3D*array3D)
print(array3D.ndim)
print(array3D.size)
print(array3D.shape)

[[[   1    4    9]
  [  64   81    0]
  [ 784  841  400]
  [3364 3481 2500]]

 [[ 121  144  169]
  [ 324  361  100]
  [1444 1521  900]
  [2304 2401 1600]]]
3
24
(2, 4, 3)


(
  two rows, two rows(inner), three colomn(each row content three colomn)
)

In [ ]:
# Access the specific element
n = 10
print(array3D[1][1][2])

10


## Matrix

In [ ]:
matrix = np.matrix([
    [1, 2],
    [11, 12]
])
print(matrix)

[[ 1  2]
 [11 12]]


In [ ]:
# Cross multiplication of matrix
mat_a = np.matrix([
    [1, 2],
    [11, 12]
])

mat_b = np.matrix([
    [3, 4],
    [0, 2]
])

mat_a * mat_b


matrix([[ 3,  8],
        [33, 68]])

In [ ]:
# duplicate or not
arr = [1, 3, 2]
bool = False
for i in arr:
  if arr.count(i) > 1:
    bool = True
    break

if bool:
  print('true')
else:
  print('false')

false


In [ ]:
def is_duplicate(arr):
  hashmap = set()
  for i in arr:
    if i in hashmap:
      return 'true'
    hashmap.add(i)

  return 'false'

is_duplicate(arr = [1,2,3,4])

'false'

arr = [1, 3, 2, 1]

In [ ]:
count = 0
arr = [1, 3, 2, 1]
boo = False
for i in range(0, len(arr)):
  for j in range(i, len(arr)):
    if arr[i] == arr[j]:
      count+=1
      if count== 2:
        boo = True
    else:
      count = 0

if boo:
  print('yes')
else:
  print('no')



yes


In [ ]:
seen = set()
is_duplicate = False

for i in arr:
  if i in seen:
    is_duplicate = True
    break
  seen.add(i)

if is_duplicate:
  print('true')
else:
  print('false')

true


## Valid Anagram

Examples:
```
Input: s="anagram", t="nagaram"
Output: true

Input: s="rat", t="car"
Output: false
```

In [ ]:
def is_anagram(s, t):
  s = list(s)
  t = list(t)
  return s == t

print(is_anagram("rat", "car"))          # Expected: False
print(is_anagram("hello", "oellh"))      # Expected: True
print(is_anagram("test", "ttew"))        # Expected: False
print(is_anagram("aabbcc", "abcabc"))    # Expected: True
print(is_anagram("aabbcc", "aabbccc"))   # Expected: False

False
False
False
False
False


In [ ]:
def is_anagram(s, t):
  if len(s) != len(t):
        return 'false'

  s = list(s)
  t = list(t)
  round1 = True
  round2 = True

  for i in s:
    if i not in t:
      round1 = False
      break

  for j in t:
    if j not in s:
      round2 = False
      break

  if round1 and round2:
    return 'true'
  else:
    return 'false'

print(is_anagram(s="anagram", t="nagaram"))

true


In [ ]:
# Test cases
print(is_anagram("anagram", "nagaram"))  # Expected: True
print(is_anagram("rat", "car"))          # Expected: False
print(is_anagram("hello", "oellh"))      # Expected: True
print(is_anagram("test", "ttew"))        # Expected: False
print(is_anagram("aabbcc", "abcabc"))    # Expected: True
print(is_anagram("aabbcc", "aabbccc"))   # Expected: False

true
false
true
false
true
false


In [ ]:
s="anagram"
t="nagaram"

print(sorted(s))

['a', 'a', 'a', 'g', 'm', 'n', 'r']


In [ ]:
def is_anagram(s, t):
    return sorted(s) == sorted(t)

# Test cases
print(is_anagram("anagram", "nagaram"))  # Expected: True
print(is_anagram("rat", "car"))          # Expected: False
print(is_anagram("hello", "oellh"))      # Expected: True
print(is_anagram("test", "ttew"))        # Expected: False
print(is_anagram("aabbcc", "abcabc"))    # Expected: True
print(is_anagram("aabbcc", "aabbccc"))   # Expected: False


True
False
True
False
True
False


In [ ]:
def is_anagram(s, t):
    if len(s) != len(t):
        return False

    char_count_s = {}
    char_count_t = {}

    for char in s:
        char_count_s[char] = char_count_s.get(char, 0) + 1

    for char in t:
        char_count_t[char] = char_count_t.get(char, 0) + 1

    return char_count_s == char_count_t

# Test cases
print(is_anagram("anagram", "nagaram"))  # Expected: True
print(is_anagram("rat", "car"))          # Expected: False
print(is_anagram("hello", "oellh"))      # Expected: True
print(is_anagram("test", "ttew"))        # Expected: False
print(is_anagram("aabbcc", "abcabc"))    # Expected: True
print(is_anagram("aabbcc", "aabbccc"))   # Expected: False


{'a': 3, 'n': 1, 'g': 1, 'r': 1, 'm': 1}
{'n': 1, 'a': 3, 'g': 1, 'r': 1, 'm': 1}
True


In [ ]:
def is_anagram(s, t):
  if len(s) != len(t):
    return False
  s_dic = {}
  t_dic = {}

  for char in s:
    s_dic[char] = s_dic.get(char, 0) + 1

  for char in t:
    t_dic[char] = t_dic.get(char, 0) + 1

  return s_dic == t_dic

# Test cases
print(is_anagram("anagram", "nagaram"))  # Expected: True
print(is_anagram("rat", "car"))          # Expected: False
print(is_anagram("hello", "oellh"))      # Expected: True
print(is_anagram("test", "ttew"))        # Expected: False
print(is_anagram("aabbcc", "abcabc"))    # Expected: True
print(is_anagram("aabbcc", "aabbccc"))   # Expected: False



True
False
True
False
True
False


## Problem list

Examples:
```
Input: nums = [2, 7, 11, 15], target = 9
Output: [0, 1]

Input: nums = [3, 2, 4], target = 6
Output: [1, 2]
```


In [ ]:
def sumNum(nums, target):
  for i in range(0, len(nums)):
    for j in range(i+1, len(nums)):
      if nums[i] + nums[j] == target:
        return [i, j]

print(sumNum(nums = [2, 7, 11, 15], target = 9))
print(sumNum(nums = [3, 2, 4], target = 6))

[0, 1]
[1, 2]


In [ ]:
def sumNum(nums, target):
  hashmap = {}

  for i, n in enumerate(nums):
    diff = target - n

    if diff in hashmap:
      return [i, hashmap[diff]]

    hashmap[n] = i

print(sumNum(nums = [2, 7, 11, 15], target = 9))
print(sumNum(nums = [3, 2, 4], target = 6))

[1, 0]
[2, 1]


## Group Anagram

```
Input: strs = ["eat", "tea", "tan", "ate", "nat", "bat"]
Output: [["bat"], ["nat", "tan"], ["ate", "eat", "tea"]]
```

In [ ]:
def group_anagram(strs):
  output = []
  for i in range(0, len(strs)):
    for j in range(i+1, len(strs)):
      if sorted(strs[i]) == sorted(strs[j]):
        output.append([strs[j]])

  return output

strs = ["eat", "tea", "tan", "ate", "nat", "bat"]

group_anagram(strs)


[['tea'], ['ate'], ['ate'], ['nat']]

In [ ]:
strs = ["eat", "tea", "tan", "ate", "nat", "bat"]
def group_anagram(strs):
  final = []
  for i in strs:
    same = [j for j in strs if sorted(i) == sorted(j)]
    final.append(same)

  output = []
  for k in final:
    if k not in output:
      output.append(k)
  return output

print(group_anagram(strs))
print(group_anagram([""]))
print(group_anagram(["a"]))

[['eat', 'tea', 'ate'], ['tan', 'nat'], ['bat']]
[['']]
[['a']]


In [ ]:
from collections import defaultdict
def group_anagram(strs):
  hashmap = defaultdict(list)

  for word in strs:
    count = [0]*26
    for char in word:
      count[ord(char) - ord('a')] += 1

    hashmap[tuple(count)].append(word)

  return hashmap.values()

print(group_anagram(strs))
print(group_anagram([""]))
print(group_anagram(["a"]))

dict_values([['eat', 'tea', 'ate'], ['tan', 'nat'], ['bat']])
dict_values([['']])
dict_values([['a']])


You are given a string s. The score of a string is defined as the sum of the absolute difference between the ASCII values of adjacent characters.

Return the score of s.



Example 1:

Input: s = "hello"

Output: 13

Explanation:

The ASCII values of the characters in s are: 'h' = 104, 'e' = 101, 'l' = 108, 'o' = 111. So, the score of s would be |104 - 101| + |101 - 108| + |108 - 108| + |108 - 111| = 3 + 7 + 0 + 3 = 13.

Example 2:

Input: s = "zaz"

Output: 50

Explanation:

The ASCII values of the characters in s are: 'z' = 122, 'a' = 97. So, the score of s would be |122 - 97| + |97 - 122| = 25 + 25 = 50.



Constraints:

2 <= s.length <= 100
s consists only of lowercase English letters.

In [ ]:
s = "hello"
count = 0
temp = 0
sum = 0
while count < (len(s)-1):
  temp = ord(s[count]) - ord(s[count+1])
  sum += abs(temp)
  count += 1
sum

13

In [ ]:
# Reset the built-in sum function if it was overwritten
del sum

# Now run the optimized code
s = "hello"
sum_of_differences = sum(abs(ord(s[i]) - ord(s[i + 1])) for i in range(len(s) - 1))
print(sum_of_differences)  # Output: 37


13


Example 1:
```
Input: nums = [1,2,2]
Output: 1
Explanation: After 1 move, the array could be [1, 2, 3].
Example 2:

Input: nums = [3,2,1,2,1,7]
Output: 6
Explanation: After 6 moves, the array could be [3, 4, 1, 2, 5, 7].
```
It can be shown with 5 or less moves that it is impossible for the array to have all unique values.

In [ ]:
nums = [3,2,1,2,1,7]
count = 0
while len(nums) != len(set(nums)):
  new = []
  for i in nums:
    if i in new:
      new.append(i+1)
      count += 1
    else:
      new.append(i)
  nums = new

print(new)
print(count)

[3, 2, 1, 4, 5, 7]
6


In [ ]:
nums = [3,2,1,2,1,7]
nums.sort()
nums

[1, 1, 2, 2, 3, 7]

In [ ]:
def minIncrementForUnique(nums):
  nums.sort()
  moves = 0
  for i in range(1, len(nums)):
      if nums[i] <= nums[i-1]:
          moves += nums[i-1] - nums[i] + 1
          nums[i] = nums[i-1]+1
  return moves

minIncrementForUnique(nums = [3,2,1,2,1,7])

6


<a href="https://cscircles.cemc.uwaterloo.ca/visualize#code=def+minIncrementForUnique(nums)%3A%0A++nums.sort()%0A++moves+%3D+0%0A++for+i+in+range(1,+len(nums))%3A%0A++++++if+nums%5Bi%5D+%3C%3D+nums%5Bi-1%5D%3A%0A++++++++++moves+%2B%3D+nums%5Bi-1%5D+-+nums%5Bi%5D+%2B+1%0A++++++++++nums%5Bi%5D+%3D+nums%5Bi-1%5D%2B1%0A++return+moves%0A%0AminIncrementForUnique(nums+%3D+%5B3,2,1,2,1,7%5D)&mode=display&raw_input=&curInstr=25">Visualize the above code</a>