<a href="https://colab.research.google.com/github/Nayan-Bebale/DSA-Practice/blob/main/3_2_arrayMatrixHashmap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Array, Matrix and hashing

<a href="https://neetcode.io/roadmap">NeetCode Roadmap</a>

In [ ]:
import numpy as np

In [ ]:
array1D = np.array([1, 2, 3, 4])
print(array1D)
print(array1D.ndim)

[1 2 3 4]
1


In [ ]:
# Access the specific element
n = 3
print(array1D[2])

3


In [ ]:
array2D = np.array([
    [1, 2, 3, 4],
    [11, 12, 13, 14],
    [21, 22, 23, 24],
    [31, 32, 33, 34]
])
print(array2D.ndim)

2


In [ ]:
# Access the specific element
n = 23
print(array2D[2][2])
print(array2D.shape)

23
(4, 4)


In [ ]:
array3D = np.array([
    [
        [1, 2, 3],
        [8, 9, 0],
        [28, 29, 20],
        [58, 59, 50]
    ],
    [
        [11, 12, 13],
        [18, 19, 10],
        [38, 39, 30],
        [48, 49, 40]
    ]
])
print(array3D*array3D)
print(array3D.ndim)
print(array3D.size)
print(array3D.shape)

[[[   1    4    9]
  [  64   81    0]
  [ 784  841  400]
  [3364 3481 2500]]

 [[ 121  144  169]
  [ 324  361  100]
  [1444 1521  900]
  [2304 2401 1600]]]
3
24
(2, 4, 3)


(
  two rows, two rows(inner), three colomn(each row content three colomn)
)

In [ ]:
# Access the specific element
n = 10
print(array3D[1][1][2])

10


## Matrix

In [ ]:
matrix = np.matrix([
    [1, 2],
    [11, 12]
])
print(matrix)

[[ 1  2]
 [11 12]]


In [ ]:
# Cross multiplication of matrix
mat_a = np.matrix([
    [1, 2],
    [11, 12]
])

mat_b = np.matrix([
    [3, 4],
    [0, 2]
])

mat_a * mat_b


matrix([[ 3,  8],
        [33, 68]])

In [ ]:
# duplicate or not
arr = [1, 3, 2]
bool = False
for i in arr:
  if arr.count(i) > 1:
    bool = True
    break

if bool:
  print('true')
else:
  print('false')

false


arr = [1, 3, 2, 1]

In [ ]:
count = 0
arr = [1, 3, 2, 1]
boo = False
for i in range(0, len(arr)):
  for j in range(i, len(arr)):
    if arr[i] == arr[j]:
      count+=1
      if count== 2:
        boo = True
    else:
      count = 0

if boo:
  print('yes')
else:
  print('no')



yes


In [ ]:
seen = set()
is_duplicate = False

for i in arr:
  if i in seen:
    is_duplicate = True
    break
  seen.add(i)

if is_duplicate:
  print('true')
else:
  print('false')

true


## Valid Anagram

Examples:
```
Input: s="anagram", t="nagaram"
Output: true

Input: s="rat", t="car"
Output: false
```

In [ ]:
def is_anagram(s, t):
  s = list(s)
  t = list(t)
  return s == t

print(is_anagram("rat", "car"))          # Expected: False
print(is_anagram("hello", "oellh"))      # Expected: True
print(is_anagram("test", "ttew"))        # Expected: False
print(is_anagram("aabbcc", "abcabc"))    # Expected: True
print(is_anagram("aabbcc", "aabbccc"))   # Expected: False

False
False
False
False
False


In [ ]:
def is_anagram(s, t):
  if len(s) != len(t):
        return 'false'

  s = list(s)
  t = list(t)
  round1 = True
  round2 = True

  for i in s:
    if i not in t:
      round1 = False
      break

  for j in t:
    if j not in s:
      round2 = False
      break

  if round1 and round2:
    return 'true'
  else:
    return 'false'

print(is_anagram(s="anagram", t="nagaram"))

true


In [ ]:
# Test cases
print(is_anagram("anagram", "nagaram"))  # Expected: True
print(is_anagram("rat", "car"))          # Expected: False
print(is_anagram("hello", "oellh"))      # Expected: True
print(is_anagram("test", "ttew"))        # Expected: False
print(is_anagram("aabbcc", "abcabc"))    # Expected: True
print(is_anagram("aabbcc", "aabbccc"))   # Expected: False

true
false
true
false
true
false


In [1]:
s="anagram"
t="nagaram"

print(sorted(s))

['a', 'a', 'a', 'g', 'm', 'n', 'r']


In [6]:
def group_anagram(strs):
  output = []
  for i in range(0, len(strs)):
    for j in range(i, len(strs)):
      if sorted(strs[i]) == sorted(strs[j]):
        output.append([strs[j]])

  return output

strs = ["eat", "tea", "tan", "ate", "nat", "bat"]

group_anagram(strs)


[['eat'],
 ['tea'],
 ['ate'],
 ['tea'],
 ['ate'],
 ['tan'],
 ['nat'],
 ['ate'],
 ['nat'],
 ['bat']]

In [ ]:
def is_anagram(s, t):
    return sorted(s) == sorted(t)

# Test cases
print(is_anagram("anagram", "nagaram"))  # Expected: True
print(is_anagram("rat", "car"))          # Expected: False
print(is_anagram("hello", "oellh"))      # Expected: True
print(is_anagram("test", "ttew"))        # Expected: False
print(is_anagram("aabbcc", "abcabc"))    # Expected: True
print(is_anagram("aabbcc", "aabbccc"))   # Expected: False


True
False
True
False
True
False


In [ ]:
def is_anagram(s, t):
    if len(s) != len(t):
        return False

    char_count_s = {}
    char_count_t = {}

    for char in s:
        char_count_s[char] = char_count_s.get(char, 0) + 1

    for char in t:
        char_count_t[char] = char_count_t.get(char, 0) + 1

    return char_count_s == char_count_t

# Test cases
print(is_anagram("anagram", "nagaram"))  # Expected: True
print(is_anagram("rat", "car"))          # Expected: False
print(is_anagram("hello", "oellh"))      # Expected: True
print(is_anagram("test", "ttew"))        # Expected: False
print(is_anagram("aabbcc", "abcabc"))    # Expected: True
print(is_anagram("aabbcc", "aabbccc"))   # Expected: False


{'a': 3, 'n': 1, 'g': 1, 'r': 1, 'm': 1}
{'n': 1, 'a': 3, 'g': 1, 'r': 1, 'm': 1}
True


In [ ]:
def is_anagram(s, t):
  if len(s) != len(t):
    return False
  s_dic = {}
  t_dic = {}

  for char in s:
    s_dic[char] = s_dic.get(char, 0) + 1

  for char in t:
    t_dic[char] = t_dic.get(char, 0) + 1

  return s_dic == t_dic

# Test cases
print(is_anagram("anagram", "nagaram"))  # Expected: True
print(is_anagram("rat", "car"))          # Expected: False
print(is_anagram("hello", "oellh"))      # Expected: True
print(is_anagram("test", "ttew"))        # Expected: False
print(is_anagram("aabbcc", "abcabc"))    # Expected: True
print(is_anagram("aabbcc", "aabbccc"))   # Expected: False



True
False
True
False
True
False


## Problem list

Examples:
```
Input: nums = [2, 7, 11, 15], target = 9
Output: [0, 1]

Input: nums = [3, 2, 4], target = 6
Output: [1, 2]
```


In [ ]:
def sumNum(nums, target):
  for i in range(0, len(nums)):
    for j in range(i+1, len(nums)):
      if nums[i] + nums[j] == target:
        return [i, j]

print(sumNum(nums = [2, 7, 11, 15], target = 9))
print(sumNum(nums = [3, 2, 4], target = 6))

[0, 1]
[1, 2]


In [ ]:
def sumNum(nums, target):
  hashmap = {}

  for i, n in enumerate(nums):
    diff = target - n

    if diff in hashmap:
      return [i, hashmap[diff]]

    hashmap[n] = i

print(sumNum(nums = [2, 7, 11, 15], target = 9))
print(sumNum(nums = [3, 2, 4], target = 6))

[1, 0]
[2, 1]
