<a href="https://colab.research.google.com/github/Nayan-Bebale/DSA-Practice/blob/main/3_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Array

## What is array?

In computer science, an array is a data structure consisting of a collection of elements, each identified by at least one array index or key. An array is stored such that the position of each element can be computed form its index by a mathematical formula.



1.   collection of same data type element.
2.   element of an array are located in a contiguous.
3. Each  element of an array has a unique index
4. The size of an array is predefined and cannot be modify.

Array :- [ 5 | 4 | 10 | 11 | 8 | 11 | 89 | 87 | 12 ]
<br>
Index:-  [0] [1] [2]  [3]  [4] [5]   [6]  [7]  [8]

## Type of Array
There are two types of array
1. One Dimenstional Array
2. Multi Dimenstional

**Creating array**

from array import *

arrayName = array(typecode, [Initializers])

---


|Type Code|	C++ Type      |	Python           |	Minimum Sizes in Bytes |
|:-------:|:-------------:|:----------------:|:-----------------------:|
|‘c’	    |char           |	character        |	1                      |
|‘b’	    |signed char    |	int              |	1                      |
|‘B’	    |unsigned char  |	int              |	1                      |
|‘u’	    |Py_UNICODE     |	unicode character|	2                      |
|‘h’	    |signed short   |	int              |	2                      |
|‘H’	    |unsigned short |	int              |	2                      |
|‘i’	    |signed int     |	int              |	2                      |
|‘I’	    |unsigned int   |	long             |	2                      |
|‘l’	    |signed long    |	int              |	4                      |
|‘L’	    |unsigned long  |	long             |	4                      |
|‘f’	    |float          |float             |	4                      |
|‘d’	    |double         |float             |	8                      |





In [ ]:
from array import array

arr1 = array('i', [1, 4, 5, 6, 7, 7, 8, 9])
print(arr1)

array('i', [1, 4, 5, 6, 7, 7, 8, 9])


<h3>Insert array</h3>

Time complexity : O(n)  [Insertion at the start of the array]
<br>*Time* complexity : O(1)  [Insertion at the end of the array]
<br>*Time* complexity : O(n)  [Insertion when array is full]

In [ ]:
# arr1[5] = 26
# arr1.insert(index, value)
arr1.insert(4, 3)
print(arr1)

array('i', [1, 4, 5, 6, 3, 7, 7, 8, 9])


<h3> Array Traversal</h3>

Time complexity : O(n)

Space complexity : O(1)

In [ ]:
for element in arr1:
  print(element, end=' ')

1 4 5 6 3 7 7 8 9 

<h3>Accessing the data</h3>

In [ ]:
def accessElement(arr, index):
  if index >= len(arr):
    print("The element out of the index")
  else:
    print(arr[index])

accessElement(arr1, 5)

7


In [ ]:
def sortElement(arr):
  for i in range(0, len(arr)):
    for j in range(1, i+1):
      if i > j:
        arr[j], arr[i] = arr[i], arr[j]

  return arr
sortElement(arr1)

array('i', [1, 9, 8, 7, 7, 3, 6, 5, 4])

In [ ]:
arr1[1]

4

<h3>Searching the data</h3>


In [ ]:
def searchElement(arr, element):
  for item in arr:
    if item == element:
      print(item)
      break
  else:
    print(f"{element} is not found.")
searchElement(arr1, 745646)

745646 is not found.


### Deleting element

In [ ]:
print(arr1)

array('i', [1, 4, 5, 6, 3, 7, 7, 8, 9])


In [ ]:
arr1.remove(9)
print(arr1)

array('i', [4, 5, 6, 7, 7, 8])


### Time and Space Complexity in One Dimensioal Arrays


|Operations                     |	Time Complexity|	Space Complexity        |
|:-----------------------------:|:--------------:|:----------------:|
|Creating an empty array	      |O(1)            |	    O(n)        |                      
|Inserting a value in an array |O(1)/ O(n)       |	O(1)              |                      
|Traversining a given array	   |O(n)             |	O(1)              |                      
|Accessing a given cell	       |O(1)             |	O(1)|                    
|Searching a given value	     |O(n)             |	O(1)              |                      
|Deleting a given value	       |O(1)/O(n)        |	O(1)              |                      
                     



**Let's analyze the time and space complexity of the operations we perform.**

1. Creating an empty array takes constant time complexity. The space complexity is O(N), as the system allocates N cells for the array.

2. Inserting a value at the end of the array has constant time complexity, while inserting at the beginning takes O(N) time complexity. The space complexity remains O(1).

3. Traversing a given array takes O(N) time complexity, visiting each element to print or update it. The space complexity is O(1).

4. Accessing a given element in the array has constant time complexity (O(1)). The space complexity is also constant.

5. Searching for a given value inside an array takes O(N) time complexity, as it requires visiting each cell. The space complexity is constant.

6. Deleting a value from the end of the array has constant time complexity, while deleting from the middle or beginning takes O(N) time complexity. The space complexity remains constant.

In summary, the rearranged information:

- Creating an empty array: Time - constant, Space - O(N)
- Inserting a value (end): Time - constant, Space - O(1)
- Inserting a value (beginning): Time - O(N), Space - O(1)
- Traversing a given array: Time - O(N), Space - O(1)
- Accessing a given element: Time - constant, Space - constant
- Searching a given value: Time - O(N), Space - constant
- Deleting a value (end): Time - constant, Space - constant
- Deleting a value (middle/beginning): Time - O(N), Space - constant

Hopefully, this provides a clearer understanding of the time and space complexities for each operation.

### Practicing of Array

1. Create an array abd traverse.

In [ ]:
arr2 = array('i', [2, 4, 5, 6, 6, 7, 6, 8, 78, 87])

for ele in arr2:
  print(ele, end=' ')

2 4 5 6 6 7 6 8 78 87 

2. Access individual elements through indexes.

In [ ]:
def accessByIndex(arr, index):
  if len(arr) > index and -len(arr) <= index:
    return arr[index]
  else:
    return "Index Outof."

print(accessByIndex(arr2, -10))

2


3. Append any value to the array using append() method.

In [ ]:
arr2.append(45)
arr2

array('i', [2, 4, 5, 6, 6, 7, 6, 8, 78, 87, 45])

4. Insert any value to the array using insert() method.

In [ ]:
# arr2.insert(index, value)
arr2.insert(0 , 5)
arr2

array('i', [5, 2, 4, 5, 6, 6, 7, 6, 8, 78, 87, 45])

5. Extend python array using extend() method.

In [ ]:
arr2.extend(arr1)
arr2

array('i', [5, 2, 4, 5, 6, 6, 7, 6, 8, 78, 87, 45, 1, 4, 5, 6, 7, 7, 8, 9])

6. Add items form list into array  using fromlist() method.

In [ ]:
lis1 = [890, 797, 342, 435, 653, 534]
arr1.fromlist(lis1)
arr1

array('i', [1, 4, 5, 6, 7, 7, 8, 9, 890, 797, 342, 435, 653, 534])

7. Remove any array element using remove() method.

In [ ]:
arr1.remove(890)
arr1

array('i', [1, 4, 5, 6, 7, 7, 8, 9, 797, 342, 435, 653, 534])

8. Remove any array element using pop() method.

In [ ]:
arr1.pop()
arr1

array('i', [1, 4, 5, 6, 7, 7, 8, 9, 797, 342, 435, 653])

9. Fetch any element throught its index using index() method.

In [ ]:
arr1.index(797)

8

10. Reverse a python array using reverse() method.

In [ ]:
arr2.reverse()
arr2

11. Get array buffer information through buffer_info() method

---
buffer_info() returns a tuple, which contains the memory address and the length of the buffer that holds the array's contents in the form (address, length).

In [ ]:
arr1.buffer_info()

(135911912251600, 12)

12. Check for number of occurrences of an element using count() method.

In [ ]:
arr1.count(7)

2

13. Convert array to string using tostring() method.

tosting() method comes under java language.

In [ ]:
test = array('i', [3, 5, 6, 7, 8, 9])

In [ ]:
# using list comprehension
listToStr = ' '.join([str(elem) for elem in test])

print(listToStr)

<class 'str'>


14. Convert array to python list with same elements using tolist() method.

In [ ]:
new = test.tolist()
type(new)

list

15. Slice Elements form an array



In [ ]:
arr1

array('i', [1, 4, 5, 6, 7, 7, 8, 9, 797, 342, 435, 653])

In [ ]:
arr1[0::2]

array('i', [1, 5, 7, 8, 797, 435])

### Two Dimensional Array

An array with a bunch of values having been declared with double index
<br>
a[i][j] --> i and j between 0 and n.

Day 1 - 11, 14, 10, 6<br>
Day 2 - 10, 14, 11, 5<br>
Day 3 - 13, 14, 12, 8<br>
Day 5 - 14, 18, 13, 9<br><br>
**When we create an array, we:**


*   Assign it to a variable
*   Define the type of elements that it will store
*   Define its size (the maximum numbers of elements)

**Time Complexity** = O(mn)
<br>
m = no. of column<br>
n = no. of row


In [1]:
import numpy as np

twoDArray = np.array([[11, 14, 10, 6],
                      [10, 14, 11, 5],
                      [13, 14, 12, 8],
                      [14, 18, 13, 9]])
print(twoDArray)

[[11 14 10  6]
 [10 14 11  5]
 [13 14 12  8]
 [14 18 13  9]]


In [ ]:
# twoDArray[row][column]
twoDArray[3][2]

13

### Insertion - Two Dimensional array

In [ ]:
# new2DArray = np.insert(arrName, index, [[elements]], axis=row(0), col(1))

new2DArray = np.insert(twoDArray, 3,[[1, 2, 3, 4]], axis=0)
print(new2DArray)

[[11 14 10  6]
 [10 14 11  5]
 [13 14 12  8]
 [ 1  2  3  4]
 [14 18 13  9]]


In [ ]:
newTwoArray = np.insert(twoDArray, 1, [[91, 82, 73, 64]], axis=1)
print(newTwoArray)

[[11 91 14 10  6]
 [10 82 14 11  5]
 [13 73 14 12  8]
 [14 64 18 13  9]]


In [ ]:
newTwoArray = np.insert(twoDArray, 1, [[91, 82, 73, 64]], axis=0)
print(newTwoArray)

[[11 14 10  6]
 [91 82 73 64]
 [10 14 11  5]
 [13 14 12  8]
 [14 18 13  9]]


In [ ]:
newTwoArray = np.insert(twoDArray, 2, [[91, 82, 73, 64]], axis=1)
print(newTwoArray)

[[11 14 91 10  6]
 [10 14 82 11  5]
 [13 14 73 12  8]
 [14 18 64 13  9]]


### Accessing the data by index.

arr[i][j]
* i ---> row
* j ---> column

In [ ]:
print(twoDArray)
def accessElement(array, rowindex, colindex):
  if rowindex >= len(array) or colindex >= len(array[0]):
    print("Out Of the index.")
  else:
    return twoDArray[rowindex][colindex]

accessElement(array=twoDArray, rowindex=2, colindex=2)

# Time Complexity:- O(1)
# Space Complexity:- O(1)

[[11 14 10  6]
 [10 14 11  5]
 [13 14 12  8]
 [14 18 13  9]]


12

### Traversing in Two D Array

row index = len(array) <br>
column index = len(array[0]) <br>

In [ ]:
for row in range(len(twoDArray)):
  for col in range(len(twoDArray[0])):
    print(twoDArray[row][col])

11
14
10
6
10
14
11
5
13
14
12
8
14
18
13
9


### Searching Element


In [ ]:
def searchTD(array, search):
  for i in range(len(array)):
    for j in range(len(array[0])):
      if search == array[i][j]:
        print(f"This is the number {search} at {i} row and {j} column.")
        return

  print(f"Not Found {search}")

searchTD(twoDArray, 12)

This is the number 12 at 2 row and 2 column.


### Deletion - Two Dimensional array

In [5]:
# newTDArray = np.delete(2DArrayName, which row or column, axis=row-0/column-1)

print(f'Before {twoDArray}')
newTDArray = np.delete(twoDArray, 1, axis=1)
print(f'After {newTDArray}')

Time Complexity : O(mn)<br>
Space Complexity : O(1)

### Time and Space Complexity of Two Dimensional Array

### Time and Space Complexity in One Dimensioal Arrays


|Operations                     |	Time Complexity|	Space Complexity        |
|:-----------------------------:|:--------------:|:----------------:|
|Creating an empty array	      |O(1)            |	    O(mn)        |                      
|Inserting a value in an array |O(1)/ O(mn)       |	O(1)              |                      
|Traversining a given array	   |O(mn)             |	O(1)              |                      
|Accessing a given cell	       |O(1)             |	O(1)|                    
|Searching a given value	     |O(mn)             |	O(1)              |                      
|Deleting a given value	       |O(1)/O(mn)        |	O(1)              |                      
                     



### When to use/avoid Arrays

**When to Use**

---


*   To store multiple variable of same data type
*   Random access

<br>

**When to avoid**

---

* Same data type elements
* Reserve memory
