<a href="https://colab.research.google.com/github/Nayan-Bebale/DSA-Practice/blob/main/5_ArrayList_InterviewQuestions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Interview Questions

Q1. Find Missing values from list.<br>
mylist = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]


In [ ]:
mylist = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
for i in range(1, 101):
  if i not in mylist:
    print(i)

73


In [ ]:
def findMissing(list, n):
    sum1 = sum(list)
    sum2 = 100*101/2
    print(sum2-sum1)


findMissing(mylist, 100)

73.0


Q2. Write a program to find all pairs of integers whose sum is equal to given number.

Example:1<br>
**Input :** nums= [2,7,11, 15], target=9<br>
<br>**Output :** [0, 1]<br>**Output :** Because nums[0] + nums[1] == 9, we return [0, 1]

In [ ]:
def pairSum(nums, sum):
  for i in range(len(nums)):
    for j in range(i, len(nums)):
      if sum == nums[i]+nums[j]:
        print([i, j])

pairSum([2,7,11,5,4,15], 9)


[0, 1]
[3, 4]


Q3. How to check if an array contains a number in python.

In [ ]:
import numpy as np

myArray = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

def findNumbers(array, num):
  if num in array:
    print(f"{num} is present")
  else:
    print(f"{num} is not present")

findNumbers(myArray, 6)

6 is present


Q4. How to find maximum product of two integers in the array where all elements are positive

In [ ]:
import numpy as np

arr1 = np.array([23, 340, 2, 25, 56, 22, 98, 34, 54, 64, 23, 64, 98, 100, 54])
add = 0
a = 0
max = 0
b = 0
for i in range(len(arr1)):
  for j in range(i+1, len(arr1)):
    add = arr1[i] + arr1[j]
    if max < add:
      max = add
      a = arr1[i]
      b = arr1[j]

print(f"Combination of {a} and {b} is the maximum product is {max}")

Combination of 340 and 100 is the maximum product is 440


In [ ]:
def findMaxProduct(array):
    maxProduct = 0
    for i in range(len(array)):
        for j in range(i+1,len(array)):
            if array[i]*array[j] > maxProduct:
                maxProduct = array[i]*array[j]
                pairs = str(array[i])+ "," + str(array[j])
    print(pairs)
    print(maxProduct)

findMaxProduct(arr1)

340,100
34000


Q5. Is Unique: Implement an algorithm to determine if a list has all unique characters, using python list.

In [ ]:
arr1 = [1, 2, 4, 5, 6, 7, 8, 9]

def checkUnique(arr1):
  for i in range(len(arr1)):
    for j in range(i+1, len(arr1)):
      if arr1[i] == arr1[j]:
        return False
  return True

checkUnique(arr1)

True

In [ ]:
def isUnique(list):
  a=[]
  for i in list:
    if i in a:
        print(i)
        return False
    else:
        a.append(i)
  return True

print(isUnique(arr1))

True


Q6. **Permutations** : any of the different ways in which a set of things can be ordered

**Example:**<br>
list1 = [1, 2, 4]
list2 = [2, 4, 1]

Its the permutations of each other.

In [ ]:
list1 = [1, 2, 4]
list2 = [2, 4, 1, 4]

def isPermutated(list1, list2):
  if len(list1) == len(list2):
    for i in list1:
      if i not in list2:
        return False
  else:
    return False
  return True

print(isPermutated(list1, list2))

False


In [ ]:
def permuntation(list1, list2):
    print(list1)
    print(list2.reverse())
    if list1 == list2:   # if list1 == list2.reverse() -- false
        return True
    else:
        return False

print(permuntation([1,2,3], [3,2,1]))

[1, 2, 3]
None
True


**Rotate Matrix**- Give 2d array represented by an NxN matrix  write a method to rotate the 2d array by 90 degrees.<br>
**Input:-**<br>
 |-----------|<br>
 |[1 2 3] |<br>
 |[4 5 6] |<br>
 |[7 8 9] |<br>
 |-----------|
<br>
**Output:-**<br>
|-----------|<br>
 |[7 4 1] |<br>
 |[8 5 2] |<br>
 |[9 6 3] |<br>
 |-----------|

In [ ]:
import numpy as np

TwoDArray = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(TwoDArray)

def rotationalMatrix(matrix):
  n = len(matrix)
  for layer in range(n//2):
    first = layer
    last = n-layer-1
    for i in range(first, last):
      # save top element
      top = matrix[layer][i]
      # move left element to top
      matrix[layer][i] = matrix[-i-1][layer]
      # move  bottom element to left
      matrix[-i-1][layer] = matrix[-layer-1][-i-1]
      # move right to bottom
      matrix[-layer-1][-i-1] = matrix[i][-layer-1]
      # move to right
      matrix[i][-layer-1] = top
  return matrix

print(rotationalMatrix(TwoDArray))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 4 1]
 [8 5 2]
 [9 6 3]]


In [ ]:
print("We will see more questions")